### ISSUE TITLE
[BUG] NullPointerException when calling QuantumMaid.quantumMaid().run() without configured HttpMaid

### ISSUE THREAD

**Issue by lestephane** [quantummaid/quantummaid#42]
**Describe the bug**
* NPE when calling `QuantumMaid.quantumMaid().run()` 
```
/home/lestephane/.sdkman/candidates/java/11.0.7-open/bin/java -javaagent:/opt/jetbrains/apps/IDEA-U/ch-0/193.6911.18/lib/idea_rt.jar=37457:/opt/jetbrains/apps/IDEA-U/ch-0/193.6911.18/bin -Dfile.encoding=UTF-8 -classpath /home/lestephane/GitRepos/todomaid-api/target/classes:/home/lestephane/.m2/repository/de/quantummaid/quantummaid/core/1.0.48/core-1.0.48.jar:/home/lestephane/.m2/repository/de/quantummaid/httpmaid/core/0.9.64/core-0.9.64.jar:/home/lestephane/.m2/repository/org/slf4j/slf4j-api/2.0.0-alpha1/slf4j-api-2.0.0-alpha1.jar:/home/lestephane/.m2/repository/ch/qos/logback/logback-classic/1.3.0-alpha5/logback-classic-1.3.0-alpha5.jar:/home/lestephane/.m2/repository/ch/qos/logback/logback-core/1.3.0-alpha5/logback-core-1.3.0-alpha5.jar:/home/lestephane/.m2/repository/com/sun/mail/javax.mail/1.6.2/javax.mail-1.6.2.jar:/home/lestephane/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar:/home/lestephane/.m2/repository/edu/washington/cs/types/checker/checker-framework/1.7.0/checker-framework-1.7.0.jar todomaid.api.Main
Exception in thread "main" java.lang.NullPointerException
	at de.quantummaid.quantummaid.QuantumMaid.renderSplash(QuantumMaid.java:112)
	at de.quantummaid.quantummaid.QuantumMaid.run(QuantumMaid.java:93)
	at de.quantummaid.quantummaid.QuantumMaid.run(QuantumMaid.java:84)
	at todomaid.api.Main.main(Main.java:7)
17:04:51.951 [main] INFO de.quantummaid.quantummaid.QuantumMaid - 
   ____                    _                   __  __       _     _ 
  / __ \                  | |                 |  \/  |     (_)   | |
 | |  | |_   _  __ _ _ __ | |_ _   _ _ __ ___ | \  / | __ _ _  __| |
 | |  | | | | |/ _` | '_ \| __| | | | '_ ` _ \| |\/| |/ _` | |/ _` |
 | |__| | |_| | (_| | | | | |_| |_| | | | | | | |  | | (_| | | (_| |
  \___\_\\__,_|\__,_|_| |_|\__|\__,_|_| |_| |_|_|  |_|\__,_|_|\__,_|


Process finished with exit code 1
```
* Same when calling `QuantumMaid.quantumMaid().withLocalHostEndpointOnPort(8080).run();`
```
/home/lestephane/.sdkman/candidates/java/11.0.7-open/bin/java -javaagent:/opt/jetbrains/apps/IDEA-U/ch-0/193.6911.18/lib/idea_rt.jar=42481:/opt/jetbrains/apps/IDEA-U/ch-0/193.6911.18/bin -Dfile.encoding=UTF-8 -classpath /home/lestephane/GitRepos/todomaid-api/target/classes:/home/lestephane/.m2/repository/de/quantummaid/quantummaid/core/1.0.48/core-1.0.48.jar:/home/lestephane/.m2/repository/de/quantummaid/httpmaid/core/0.9.64/core-0.9.64.jar:/home/lestephane/.m2/repository/org/slf4j/slf4j-api/2.0.0-alpha1/slf4j-api-2.0.0-alpha1.jar:/home/lestephane/.m2/repository/ch/qos/logback/logback-classic/1.3.0-alpha5/logback-classic-1.3.0-alpha5.jar:/home/lestephane/.m2/repository/ch/qos/logback/logback-core/1.3.0-alpha5/logback-core-1.3.0-alpha5.jar:/home/lestephane/.m2/repository/com/sun/mail/javax.mail/1.6.2/javax.mail-1.6.2.jar:/home/lestephane/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar:/home/lestephane/.m2/repository/edu/washington/cs/types/checker/checker-framework/1.7.0/checker-framework-1.7.0.jar todomaid.api.Main
Exception in thread "main" java.lang.NullPointerException
	at de.quantummaid.httpmaid.endpoint.purejavaendpoint.PureJavaEndpoint.lambda$pureJavaEndpointFor$1(PureJavaEndpoint.java:53)
	at de.quantummaid.quantummaid.EndpointCreator.lambda$pureJavaEndpointCreator$0(EndpointCreator.java:31)
	at de.quantummaid.quantummaid.QuantumMaid.lambda$run$1(QuantumMaid.java:90)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at de.quantummaid.quantummaid.QuantumMaid.run(QuantumMaid.java:90)
	at de.quantummaid.quantummaid.QuantumMaid.run(QuantumMaid.java:84)
	at todomaid.api.Main.main(Main.java:7)

```

**To Reproduce**
- `QuantumMaid.quantumMaid().run();`
- `QuantumMaid.quantumMaid().withLocalHostEndpointOnPort(8080).run();`

**Expected behavior**
- If quantummaid cannot run() until it has a configured httpmaid, then I should not be able to 
compile a program where I'm run()-ning without configuring httpmaid (withHttpMaid())  

* project version used: core 1.0.48 (from BOM 1.0.48)

**Comment by quantummaiddeveloper** [comment]
This cannot happen anymore because QuantumMaid will create its own HttpMaid instance.
